services:
  - type: web
    name: pcfix-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server-postgres.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: SENSITIVE_DATA_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@pcfix.local
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: https://pcfix-sistema.onrender.com,https://pcfixcomitan.onrender.com
      - key: WHATSAPP_APP_SECRET
        sync: false

  - type: web
    name: pcfix-sistema
    runtime: static
    rootDir: .
    buildCommand: ""
    staticPublishPath: .
